module.exports = {
    // TOKEN OF DISCORD APPLICATION
    TOKEN: '',
    // SERVER ID
    SERVER_ID: '',
    // CHANNEL FOR WELCOME MESSAGES
    DEFAULT_CH: '',
    // CHANNEL FOR DEBUG/INFO MESSAGES
    BOT_CH: '',
    // ID OF ADMIN USER
    BOT_ADMIN: '',
    // PATH TO RADIO START.SH
    RADIO_START: '',
    // YOUTUBE API KEY
    YOUTUBE_KEY: '',
    // TWITTER API KEY
    TWITTER_API: {
        CONSUMER_KEY: '',
        CONSUMER_SECRET: '',
        ACCESS_TOKEN_KEY: '',
        ACCESS_TOKEN_SECRET: ''
    },
    // SEND MORE DEBUG MESSAGES
    DEBUG: false
};